#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.
# The installed server listens to port 80 (HTTP) for connection
# And serves a default page index.html on the HTTP  GET request.

sudo apt-get update -y

sudo apt-get install nginx -y

# Configuration
mkdir /etc/nginx/html

# Creating Sample Page
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html

# Creating the Server Block File
echo "server { 
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
